on:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    environment: copilot
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure .netrc for private repo access
        run: |
          cat <<EOF >> ~/.netrc
          machine github.com
            login timrogers
            password ${{ secrets.DOWNLOAD_MCP_SERVER_PAT }}
          EOF
          chmod 600 ~/.netrc

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Copilot code review MCP Server
        run: npm install github:github/copilot-code-review-mcp-server