on:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    environment: copilot
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure .npmrc for GitHub Packages access
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@github:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Copilot code review MCP Server
        run: npm install @github/copilot-code-review-mcp-server
